version: "3"
services:
  db:
    image: postgres:11.5
    environment:
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=movies
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      PY_AUTORELOAD: true
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    command:
      /bin/bash -c "pip install -r requirements.txt; invoke run"
    links:
      - db
      - rabbitmq
    ports:
      - "8000:80"
  rabbitmq:
    image: rabbitmq
  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    command:
      /bin/bash -c "pip install -r requirements.txt; celery -A config.celery worker -l INFO"
    links:
      - db
      - rabbitmq
    expose:
      - "8000"
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    links:
      - db
      - web
      - celery
      - rabbitmq
    ports:
      - "80:80"
    volumes:
      - .:/src
      - ./static:/static

volumes:
  pgdata: