version: "3"
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    command:
      /bin/bash -c "pip install -r requirements.txt; invoke run"
    ports:
      - "8000:8000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
        - web
    volumes:
      - .:/src
      - ./static:/static:ro
    ports:
      - "80:80"