version: "3"
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    command:
      /bin/bash -c "pip install -r requirements.txt; invoke run"
    ports:
      - "8000:8000"
  rabbitmq:
    image: rabbitmq
  celery:
    build: .
    env_file:
      - .env
    volumes:
      - .:/src
      - ./static:/static
      - ./media:/media
    command:
      /bin/bash -c "pip install -r requirements.txt; celery -A config.celery worker -l INFO"
    links:

      - rabbitmq
    expose:
      - "8000"
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    links:
      - web
    volumes:
      - .:/src
      - ./static:/static:ro
    ports:
      - "80:80"