version: 2.1

jobs:
  deploy-prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "update apt"
          command: "sudo apt-get update"
      - run:
          name: "Install python3-pip"
          command: "sudo apt-get install python3-pip"

      - run:
          name: "install deploy requierements"
          command: "pip3 install pexpect boto3"

      - add_ssh_keys:
          fingerprints:
            - "df:54:1e:5f:1a:07:f1:2e:cd:76:45:fd:a0:98:2d:91"

      - run:
          name: "start deploy"
          command: "python3 deploy.py"


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy-prod:
    jobs:
      - deploy-prod
